# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/dev/vulkan/mastering-graphics-programming/triangle

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/dev/vulkan/mastering-graphics-programming/triangle

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/dev/vulkan/mastering-graphics-programming/triangle/CMakeFiles /mnt/dev/vulkan/mastering-graphics-programming/triangle//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/dev/vulkan/mastering-graphics-programming/triangle/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Shaders

# Build rule for target.
Shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Shaders
.PHONY : Shaders

# fast build rule for target.
Shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shaders.dir/build.make CMakeFiles/Shaders.dir/build
.PHONY : Shaders/fast

#=============================================================================
# Target rules for targets named Triangle

# Build rule for target.
Triangle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Triangle
.PHONY : Triangle

# fast build rule for target.
Triangle/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/build
.PHONY : Triangle/fast

debugshit.o: debugshit.cpp.o
.PHONY : debugshit.o

# target to build an object file
debugshit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/debugshit.cpp.o
.PHONY : debugshit.cpp.o

debugshit.i: debugshit.cpp.i
.PHONY : debugshit.i

# target to preprocess a source file
debugshit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/debugshit.cpp.i
.PHONY : debugshit.cpp.i

debugshit.s: debugshit.cpp.s
.PHONY : debugshit.s

# target to generate assembly for a file
debugshit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/debugshit.cpp.s
.PHONY : debugshit.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/main.cpp.s
.PHONY : main.cpp.s

p_device.o: p_device.cpp.o
.PHONY : p_device.o

# target to build an object file
p_device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/p_device.cpp.o
.PHONY : p_device.cpp.o

p_device.i: p_device.cpp.i
.PHONY : p_device.i

# target to preprocess a source file
p_device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/p_device.cpp.i
.PHONY : p_device.cpp.i

p_device.s: p_device.cpp.s
.PHONY : p_device.s

# target to generate assembly for a file
p_device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/p_device.cpp.s
.PHONY : p_device.cpp.s

presentation.o: presentation.cpp.o
.PHONY : presentation.o

# target to build an object file
presentation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/presentation.cpp.o
.PHONY : presentation.cpp.o

presentation.i: presentation.cpp.i
.PHONY : presentation.i

# target to preprocess a source file
presentation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/presentation.cpp.i
.PHONY : presentation.cpp.i

presentation.s: presentation.cpp.s
.PHONY : presentation.s

# target to generate assembly for a file
presentation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/presentation.cpp.s
.PHONY : presentation.cpp.s

requirement.o: requirement.cpp.o
.PHONY : requirement.o

# target to build an object file
requirement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/requirement.cpp.o
.PHONY : requirement.cpp.o

requirement.i: requirement.cpp.i
.PHONY : requirement.i

# target to preprocess a source file
requirement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/requirement.cpp.i
.PHONY : requirement.cpp.i

requirement.s: requirement.cpp.s
.PHONY : requirement.s

# target to generate assembly for a file
requirement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Triangle.dir/build.make CMakeFiles/Triangle.dir/requirement.cpp.s
.PHONY : requirement.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Shaders"
	@echo "... Triangle"
	@echo "... debugshit.o"
	@echo "... debugshit.i"
	@echo "... debugshit.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... p_device.o"
	@echo "... p_device.i"
	@echo "... p_device.s"
	@echo "... presentation.o"
	@echo "... presentation.i"
	@echo "... presentation.s"
	@echo "... requirement.o"
	@echo "... requirement.i"
	@echo "... requirement.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

